### ISSUE TITLE
gallery パッケージの作成

### ISSUE THREAD

**Issue by DaigoWakabayashi** [KosukeSaigusa/flutterfire-commons#15]
## 概要

- gallery のパッケージを作る

**Comment by hndrr** [comment]
@DaigoWakabayashi 
すみません、自分のタスクもgallery配下なんですがこちらどういう構成の予定ですか？

**Comment by KosukeSaigusa** [comment]
いったん gallery のパッケージだけ作ったものを PR 作成してもらって、それを main にマージ

その後ダイゴくんは 

1. `packages/gallery/lib/src/ダイゴくんが開発する機能名/*.dart`（切り出して利用者に提供できる形にできる機能がありそうなら開発する、なければ 2 だけでも良い）
2. `packages/gallery/example/lib/ダイゴくんが開発する機能名/*.dart`（主にサンプルアプリとして作る）

ほんださんは

1. `packages/gallery/lib/src/ほんださんが開発する機能名/*.dart`（切り出して利用者に提供できる形にできる機能がありそうなら開発する、なければ 2 だけでも良い）
2. `packages/gallery/example/lib/ほんださんが開発する機能名/*.dart`（主にサンプルアプリとして作る）

でそれぞれお願いします！

改めて尋ねられれて、2 の作業場所が若干重なっているのでもっともな指摘だと思いましたが！

ので、main.dart の最初の MyHomePage に、タップしてそれぞれのサンプルへの遷移をする ListView.builder で ListTile を雑に 2 つ並べて、上記のように `example/lib/それぞれの機能名/*.dart` で開発で触るファイルは完全に分かれている、みたいな状況にすると良さそうでしょうか？

**Comment by DaigoWakabayashi** [comment]
承知です！

@hndrr 


> いったん gallery のパッケージだけ作ったものを PR 作成してもらって、それを main にマージ

ここ自分やってみます！ 💪

**Comment by hndrr** [comment]
@DaigoWakabayashi @KosukeSaigusa 
承知しました。ありがとうございます!　よろしくお願いします！

**Comment by DaigoWakabayashi** [comment]
@hndrr 
一旦この issue は close します！
残りはそれぞれ issue 作って上記の対応進めていきましょう 🙌
